spring:
  application:
    name: turbine

turbine:
  aggregator:
    cluster-config: default
  app-config: feign-service #配置Eureka中的serviceId列表，表明监控哪些服务
  cluster-name-expression: new String("default")

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


